apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo
spec:
  jetstream:
    version: latest # Do NOT use "latest" but a specific version in your real deployment
