apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: argo
spec:
  service:
    ports:
    - name: example
      port: 12000
      targetPort: 12000
    - name: example-without-api-credentials
      port: 13000
      targetPort: 13000
  selector:
    eventsource-name: github          # event source name
  github:
    argo-combined-app:                          # event name
      repositories:
        - owner: majoferenc
          names:
            - demo-cicd-automation-app
      webhook:
        endpoint: /argo-combined-app
        port: "12000"
        method: POST
        url: https://9cb4-84-245-120-213.ngrok-free.app
      events:
        - "*"
      apiToken:
        name: git-credentials-secret
        key: .git-credentials
      insecure: true
      active: true
      contentType: json
